apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2nd-wave
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mkoellges/company.git
    targetRevision: HEAD
    path: 2nd-wave
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
