apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/she-ag/tools/kind/k8s-deployments.git
    targetRevision: manni
    path: logging
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
