---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: logging
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - Validate=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  source:
    repoURL: https://she-informationstechnologie.github.io/charts/
    chart: opensearch-cluster
    targetRevision: 1.0.3
    helm:
      values: |
        opensearch-cluster:
          cluster:
            dashboards:
              version: 2.17.1
            general:
              version: 2.17.1
              monitoring:
                tlsConfig:
                  insecureSkipVerify: true
            #   snapshotRepositories:
            #     - name: "snapshot-repo"
            #       type: "s3"
            #       settings:
            #         bucket: "opensearch"
            #         endpoint: "https://minio.minio.svc.cluster.local:9000"
            #         pathStyleAccess: "true"
            #         protocol: "https"
            #         maxRetries: "3"
            #         accessKey: "opensearch"
            #   keystore:
            #     - secret:
            #         name: "opensearch-s3-secret"
            #   keystoreSecrets: 
            #     - secretName: "opensearch-s3-secret"
            #       keys:
            #         - opensearch.s3.client.default.access_key
            #         - opensearch.s3.client.default.secret
            nodePools:
              - component: nodes
                replicas: 3
                diskSize: "10Gi"
                jvm: -Xmx4096M -Xms4096M
                resources:
                  requests:
                    memory: "4Gi"
                    cpu: "1"
                  limits:
                    memory: "10Gi"
                    cpu: "4"
                persistence:
                  pvc:
                    accessModes:
                      - ReadWriteOnce
                    storageClass: standard
                roles:
                  - "cluster_manager"
                  - "data"
                  - "ingest"
                  - "master"
                pdb:
                  enable: true
                  maxUnavailable: 1
            ingress:
              dashboards:
                enabled: true
                className: "nginx-internal"
                hosts:
                  - host: opensearch.she-test.com
                    paths:
                      - path: /
                        pathType: ImplementationSpecific
                tls:
                  - hosts:
                      - opensearch.she-test.com
                    secretName: ingress-wildcard-she
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/mkoellges/company.git
    targetRevision: HEAD
    path: logging/opensearch/
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  destination:
    name: in-cluster
    namespace: logging
