apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-opensearch
  namespace:  argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  source:
    repoURL: https://she-informationstechnologie.github.io/charts/
    chart: logging-opensearch
    targetRevision: 1.2.1
    helm:
      values: |
        opensearch:
          settings:
            nodePools:
              - component: nodes
                replicas: 3
                diskSize: "2Gi"
                persistence:
                  pvc:
                    accessModes:
                      - ReadWriteOnce
                    storageClass: standard
                nodeSelector:
                roles:
                  - "cluster_manager"
                  - "data"
                  - "ingest"
                pdb:
                  enable: true
                  maxUnavailable: 1
          # ingress:
          #   enabled: true
          #   className: "nginx-internal"
          #   hosts:
          #     - host: opensearch.koellgma.de
          #       paths:
          #         - path: /
          #           pathType: ImplementationSpecific
          #   tls:
          #     - hosts:
          #         - opensearch.koellgma.de
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
