apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-opensearch
  namespace:  argocd
spec:
  project: default
  destination:
    server: "https://kubernetes.default.svc"
    namespace: logging
  source:
    repoURL: https://she-informationstechnologie.github.io/charts/
    chart: logging-opensearch
    targetRevision: 1.2.1
    helm:
      values: |
        fluentbit:
          logLevel: warn
          config:
            inputs: |
              [INPUT]
                  Name tail
                  Path /var/log/containers/*.log
                  Exclude_Path *ingress-nginx*
                  Tag kube.*
                  multiline.parser cri
                  Mem_Buf_Limit 5m
                  Skip_Long_Lines On
                  Buffer_Chunk_Size 15m
                  Buffer_Max_Size 64m
          
              [INPUT]
                  Name tail
                  Path /var/log/containers/*ingress*.log
                  Tag ingress-nginx.*
                  Parser cri
                  Mem_Buf_Limit 5m
                  Buffer_Chunk_Size 15m
                  Buffer_Max_Size 64m

            filters: |
              [FILTER]
                  Name parser
                  Match ingress-nginx.*
                  Parser docker_no_time
                  Key_Name message
                  Preserve_Key true
        
              [FILTER]
                  Name kubernetes
                  Match kube.*
                  Merge_Log On
                  Keep_Log Off
                  K8S-Logging.Parser On
                  K8S-Logging.Exclude Off

            outputs: |
              [OUTPUT]
                  Name opensearch
                  Match kube.*
                  Host opensearch-cluster.logging.svc
                  Port 9200
                  Index container-%Y.%m
                  Retry_Limit 3
                  Suppress_Type_Name On
                  tls On
                  tls.verify Off
                  HTTP_User fluentbit
                  HTTP_Passwd ${password}
                  Trace_Error On
                  Replace_Dots On
                  Buffer_Size 2MB
          
              [OUTPUT]
                  Name opensearch
                  Match ingress-nginx.*
                  Host opensearch-cluster.logging.svc
                  Port 9200
                  Index access-logs-%Y.%m
                  Retry_Limit 3
                  Suppress_Type_Name On
                  tls On
                  tls.verify Off
                  HTTP_User fluentbit
                  HTTP_Passwd ${password}
                  Trace_Error On
                  Replace_Dots On
                  Buffer_Size 2MB

            customParsers: |
              [PARSER]
                  Name docker_no_time
                  Format json
                  Time_Keep Off
                  Time_Key time
                  Time_Format %Y-%m-%dT%H:%M:%S.%L

              [PARSER]
                  Name        accesslogs
                  Format      regex
                  Regex       ^(?<remote_addr>[^ ]*) - (?<remote_user>[^ ]*) \[(?<timestamp>[^\]]*)\] "(?<request_method>[^ ]*) (?<request_uri>[^ ]*) (?<http_version>[^ ]*)"\s(?<status>\d{3}) (?<body_bytes_sent>\d+)\s"(?<referer>[^"]*)"\s"(?<user_agent>[^"]*)"\s"(?<request_duration>[^"]*)"\s"(?<request_processing_time>[^"]*)"\s"(?<response_processing_time>[^"]*)"\s"(?<wait_time>[^"]*)"\s"(?<upstream_response_time>[^"]*)"

        opensearch:
          enabled: true
          settings:
            security:
              tls:
                http:
                  generate: true
                  secret:
                    name: opensearch-tls
            nodePools:
              - component: nodes
                replicas: 3
                diskSize: "5Gi"
                persistence:
                  pvc:
                    accessModes:
                      - ReadWriteOnce
                    storageClass: standard
                nodeSelector:
                roles:
                  - "cluster_manager"
                  - "data"
                  - "ingest"
                pdb:
                  enable: true
                  maxUnavailable: 1
          ingress:
            enabled: true
            className: "nginx-internal"
            annotations:
              nginx.ingress.kubernetes.io/proxy-body-size: "0"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              cert-manager.io/cluster-issuer: "letsencrypt-prod"

            hosts:
              - host: opensearch.example.com
                paths:
                  - path: /
                    pathType: ImplementationSpecific
            tls:
              - hosts:
                  - opensearch.example.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
