apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
  namespace: logging
type: Opaque
stringData:
  internal_users.yml: |
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2a$12$XzTAhv8X/H2FsOdESagnuOuhR.Zgn7/aFCevP.Tjz/2Ttf7Jw79Zq
      reserved: true
      backend_roles:
      - "admin"
      description: "admin user"