apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
  namespace: logging
type: Opaque
stringData:
  internal_users.yml: |
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2a$12$FcGNqTwjV..nCWuoD8vOLu3LpzZ17pTtkVfea.JHDf2o4e./DB4ca"
      reserved: true
      backend_roles:
      - "admin"
      description: "admin user"