apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
  namespace: logging
type: Opaque
stringData:
  internal_users.yml: |
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2a$12$mDs7H.HXMdHdtJCTJmpEKeOp2W/XX3LaxatNa8PdXdyrJTxF6mPNe"
      reserved: true
      backend_roles:
      - "admin"
      description: "admin user"