apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgresql-01
  namespace: databases
spec:
  shutdown: false
  standby:
    enabled: false
    repoName: repo1
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.3.1-0
  proxy:
    pgBouncer:
      replicas: 3
      config:
        global:
          max_client_conn: '250'
          default_pool_size: '250'
          max_db_connections: '250'
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: postgres-operator.crunchydata.com/role
                    operator: In
                    values:
                      - pgbouncer
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/database
                    operator: Exists
      tolerations:
        - effect: NoSchedule
          key: dedicated
          value: database
          operator: Equal
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          effective_cache_size: 64MB
          shared_buffers: 64MB
          work_mem: 16MB
          max_connections: 250
        pg_hba:
          - "hostssl all postgres 0.0.0.0/0 cert"
          - "hostssl all postgres ::/0 cert"
          - "host postgres readaccess all scram-sha-256"
  users:
    - name: she-admin
      options: SUPERUSER
      password:
        type: ASCII
  postgresVersion: 15
  instances:
    - name: cluster1
      replicas: 3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: postgres-operator.crunchydata.com/role
                    operator: In
                    values:
                      - master
              topologyKey: kubernetes.io/hostname
      dataVolumeClaimSpec:
        storageClassName: standard
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 20Gi
  backups:
    pgbackrest:
      manual:
        repoName: repo1
        options:
          - --type=full
      configuration:
        - secret:
            name: postgres-db-s3-credentials
        - configMap:
            name: pgbackrest-async-config
      global:
        log-level-console: info
        log-level-file: detail
        log-level-stderr: info
        repo1-retention-full: '2'
        repo1-retention-diff: '12'
        repo1-retention-full-type: count
        repo1-s3-uri-style: path
        repo1-path: /pgbackrest
        repo1-bundle: "y"
        repo1-bundle-limit: 10MiB
        repo1-bundle-size: 100MiB
        repo1-storage-verify-tls: "n"
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            differential: "0 5 * * 1-6"
          s3:
            bucket: postgres
            endpoint: https://minio.minio.svc.cluster.local:9000
            region: eu-01
