apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  accessMode: ReadWrite
  config:
    region: eu-01
    s3ForcePathStyle: "true"
    s3Url: https://minio.minio.svc.cluster.local:9000
    insecureSkipTLSVerify: "true"
  credential:
    key: cloud
    name: velero-s3-credentials
  default: true
  objectStorage:
    bucket: velero
    prefix: dev
  provider: aws
