apiVersion: v1
kind: Secret
metadata:
  name: opensearch-s3-secret
  namespace: logging
type: Opaque
stringData:
  opensearch.s3.client.default.secret: "password1234"
  opensearch.s3.client.default.access_key: "opensearch"
