apiVersion: v1
kind: Secret
metadata:
  name: securityconfig-secret
  namespace: logging
type: Opaque
stringData:
  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      hash: "$2a$12$O.1G.cXy5cwoTAScV221a.vgZqrTKtIsDBTXikHFGlw0M0R0Ca6za"
      reserved: true
      backend_roles:
      - "admin"
      description: "admin user"