apiVersion: v1
kind: Secret
metadata:
  name: devops-user-password
  namespace: logging
  annotations:
    opensearchuser/name: devops
    opensearchuser/namespace: logging
type: Opaque
stringData:
  password: isiph2sie4eiZieghie3aiB5asephahf
